name: Build and Push ARM Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '19 7 * * *'  # 定时每小时运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clone repository
      run: git clone https://github.com/RockChinQ/free-one-api.git repo

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '20'    
    - name: Install dependencies
      run: |
          cd repo/web
          npm install
    - name: Build web
      run: |
          cd repo/web
          npm run build
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./repo  # 这里是您clone下来的存储库路径
        push: true
        tags: cym31152x/gptapi:latest
        platforms: linux/arm/v8
